export const COUNTRIES = [
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "SA", name: "Saudi Arabia" },
	{ code: "QA", name: "Qatar" },
	{ code: "KW", name: "Kuwait" },
	{ code: "OM", name: "Oman" },
	{ code: "BH", name: "Bahrain" },
	{ code: "JO", name: "Jordan" },
	{ code: "LB", name: "Lebanon" },
	{ code: "EG", name: "Egypt" },
	{ code: "SY", name: "Syria" },
	{ code: "IQ", name: "Iraq" },
	{ code: "YE", name: "Yemen" },
	{ code: "PS", name: "Palestine" },
	{ code: "MA", name: "Morocco" },
	{ code: "TN", name: "Tunisia" },
	{ code: "DZ", name: "Algeria" },
	{ code: "LY", name: "Libya" },
	{ code: "SD", name: "Sudan" },
	{ code: "US", name: "United States" },
	{ code: "GB", name: "United Kingdom" },
	{ code: "CA", name: "Canada" },
	{ code: "AU", name: "Australia" },
	{ code: "IN", name: "India" },
	{ code: "PK", name: "Pakistan" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "TR", name: "Turkey" },
	{ code: "IR", name: "Iran" },
	{ code: "AF", name: "Afghanistan" },
] as const;

export const DEFAULT_CURRENCY = "AED";

export const CURRENCIES = [
	{ code: "AED", symbol: "د.إ", name: "UAE Dirham" },
	{ code: "SAR", symbol: "ر.س", name: "Saudi Riyal" },
	{ code: "QAR", symbol: "ر.ق", name: "Qatari Riyal" },
	{ code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
	{ code: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
	{ code: "BHD", symbol: "د.ب", name: "Bahraini Dinar" },
	{ code: "JOD", symbol: "د.أ", name: "Jordanian Dinar" },
	{ code: "LBP", symbol: "ل.ل", name: "Lebanese Pound" },
	{ code: "EGP", symbol: "ج.م", name: "Egyptian Pound" },
	{ code: "USD", symbol: "$", name: "US Dollar" },
	{ code: "EUR", symbol: "€", name: "Euro" },
	{ code: "GBP", symbol: "£", name: "British Pound" },
] as const;